#!/bin/bash
#PBS -l walltime=1:00:00
#PBS -l select=1:ngpus=1
#PBS -q normal
#PBS -P 12004268
#PBS -N survival_analysis
#PBS -j oe
#PBS -o /home/users/ntu/giabaoca/myProject-12004268/giabao/survival-analysis/out-run.txt

cd /home/users/ntu/giabaoca/myProject-12004268/giabao/survival-analysis #need to change directory to the project folder first

#activating conda environment
source activate base
conda activate testenv

#check
conda info --envs

nvidia-smi -L
echo $CUDA_VISIBLE_DEVICES

TORCH_LOGS="+dynamo"
TORCHDYNAMO_VERBOSE=1

#run the file
export VLLM_WORKER_MULTIPROC_METHOD=spawn; CUDA_VISIBLE_DEVICES=0 python3 run.py
